databases:
  - name: db-west-library
    plan: free
    databaseName: west_library
    user: rangelgs

services:
  - type: web
    plan: free
    name: westlibrary
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-west-library
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4